### ISSUE TITLE
S12 

### ISSUE THREAD

**Issue by MarcialSanchis-Agudo** [Computational-Turbulence-Group/SURD#1]
Bon dia @ms-alvaro ,

Estoy escribiendo el paper que hablamos, revisando tu manuscript en arxiv no me queda claro S12, creo que la probabilidad condicionada debe ser al reves ya que p(A|B) no es igual a p(B|A). Qué opinas?

Sino es así, entiendo que S12 es correcta cuando multiplicamos la specific mutual information por p(q_j).  

Pagina 25 pdf, 4 del Supplement.

Un saludo,

Marcial

**Comment by ms-alvaro** [comment]
Hola Marcial,

La definición utilizada en la Ecuación (S12) corresponde a la *specific mutual information*, propuesta por [De Weese & Meister (1999)](https://iopscience.iop.org/article/10.1088/0954-898X/10/4/303):

```math
\tilde{\imath}(Q_j^+ = q_j^+; \boldsymbol{Q}_{\boldsymbol{i}}) = \sum_{\boldsymbol{q}_{\boldsymbol{i}}} p(\boldsymbol{q}_{\boldsymbol{i}} | q_j^+) \log_2\left( \frac{p(q_j^+ | \boldsymbol{q}_{\boldsymbol{i}})}{p(q_j^+)} \right) \geq 0
```

Utilizando la definición de probabilidad condicional, $`p(\boldsymbol{q}_{\boldsymbol{i}}|q_j^+)={p(\boldsymbol{q}_{\boldsymbol{i}},q_j^+)}/{p(q_j^+)}`$, esta expresión se puede reescribir como:

```math
\tilde{\imath}(Q_j^+ = q_j^+; \boldsymbol{Q}_{\boldsymbol{i}}) = \sum_{\boldsymbol{q}_{\boldsymbol{i}}} \frac{p(\boldsymbol{q}_{\boldsymbol{i}}, q_j^+)}{p(q_j^+)} \log_2\left( \frac{p(q_j^+ | \boldsymbol{q}_{\boldsymbol{i}})}{p(q_j^+)} \right) \geq 0
```

Por lo tanto, al multiplicar esta cantidad por $p(q_j^+)$ y sumando sobre todos los posibles estados $q_j^+$, se recupera la expresión para la *mutual information* de la Ecuación (S8):

```math
I(Q_j^+; \boldsymbol{Q}_{\boldsymbol{i}}) = \sum_{q_j^+} p(q_j^+) \tilde{\imath}(q_j^+; \boldsymbol{Q}_{\boldsymbol{i}}) = \sum_{q_j^+, \boldsymbol{q}_i} p(q_j^+, \boldsymbol{q}_i) \log_2 \left( \frac{p(q_j^+ | \boldsymbol{q}_i)}{p(q_j^+)} \right)
```
